site_name: PyRMachines
repo_url: https://github.com/guilhermehathy/pyrmachines
repo_name: PyRMachines
theme:
  name: material
  language: pt-BR
  logo: img/rmachines-hex-01.png
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [pyrmachines]
